build:
	cd ./build;
	make -j;
	mv labwork ../;
	cd ../;
# the way to copy image from server to local by using ssh
sync:
	scp -P 22222 student2@ictlab.usth.edu.vn:/storage/student2/github/advancedhpc2019/labwork/*.jpg .

# access to server
access:
	ssh -p 22222 student2@ictlab.usth.edu.vn
